# Generated by Django 4.0.4 on 2022-04-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('advertiser', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
